### ISSUE TITLE
請幫我把同村里各投票所的票數加總

### ISSUE THREAD

**Issue by wdzeng** [electioncommittee/DataImporter#1]
如題。 2020 年和 2016 年的投票沒有這樣的問題。請幫我處理 2012 年總統選舉就好（立委上次已經處理完了）。該檔案位在 `res/export/psd2012_polling_space.txt` 。完成後請將該檔案重新命名為 `psd2012.txt` 。

**Comment by wdzeng** [comment]
剛剛把 2014 和 2018 地方選舉的資料弄好了。中選會把直轄市和省轄市的資料分開，檔案名稱後綴有 `munic` 者是直轄市、 `prov` 省轄市。也請幫我加總以下檔案：
- `res/export/lcl2018_munic.txt`
- `res/export/lcl2014_munic.txt`
- `res/export/lcl2018_prov.txt`
- `res/export/lcl2014_prov.txt`

**Comment by wdzeng** [comment]
2009 和 2010 的地方選舉資料也處理好了。也請幫我加總。

**Comment by k99521pphh** [comment]
> 剛剛把 2014 和 2018 地方選舉的資料弄好了。中選會把直轄市和省轄市的資料分開，檔案名稱後綴有 `munic` 者是直轄市、 `prov` 省轄市。也請幫我加總以下檔案：
> 
> * `res/export/lcl2018_munic.txt`
> * `res/export/lcl2014_munic.txt`
> * `res/export/lcl2018_prov.txt`
> * `res/export/lcl2014_prov.txt`

done

**Comment by k99521pphh** [comment]
all done
